rule apply_vqsr:
    input:
        vcf="test.vcf",
    output:
        idx="test.vcf.idx",
    log:
        "logs/gatk/indexfeaturefile.log",
    params:
        mode="SNP",  # set mode, must be either SNP, INDEL or BOTH
        extra="",  # optional
    resources:
        mem_mb=1024,
    wrapper:
        "master/bio/gatk/indexfeaturefile"
