name: gatk IndexFeatureFile
url: https://gatk.broadinstitute.org/hc/en-us/articles/360037428111-IndexFeatureFile
description: |
  Run gatk IndexFeatureFile.
authors:
  - Hatem Nawar
input:
  - Feature file (eg., VCF or BED file) to index. Must be in a tribble-supported format
output:
  - The output index file
notes: |
  * The `java_opts` param allows for additional arguments to be passed to the java compiler, e.g. "-XX:ParallelGCThreads=10" (not for `-XmX` or `-Djava.io.tmpdir`, since they are handled automatically).
  * The `extra` param allows for additional program arguments.
